FROM node:24-alpine

RUN apk add --no-cache python3 py3-pip ffmpeg bash git build-base \
    && python3 -m ensurepip \
    && pip3 install --no-cache-dir yt-dlp moviepy

WORKDIR /app

RUN npm i -g pnpm 

COPY package.json pnpm-lock.yaml* ./

RUN pnpm install

COPY src src
COPY .env .

CMD ["pnpm", "dev"]
