services:
  auth-service:
    environment:
      DENO_ENV: development
    command: "deno task inspect"
    working_dir: /app
    ports:
      - "3569:8000"
      - "9230:9229" # Deno inspector
    develop:
      watch:
        - path: ../auth-service
          target: /app
          action: sync
        - path: ../shared
          target: /app/shared
          action: sync

  frontend:
    environment:
      DENO_ENV: development
    ports:
      - "3500:5173"
      - "9229:9229" # Deno inspector per Zed
    develop:
      watch:
        - path: ../frontend
          target: /app
          action: sync
        - path: ../shared
          target: /app/shared
          action: sync

  telegram-bot:
    environment:
      DENO_ENV: development
    ports:
      - "9231:9229" # Deno inspector
    develop:
      watch:
        - path: ../telegram-bot
          target: /app
          action: sync
        - path: ../shared
          target: /app/shared
          action: sync
  recipe-generator:
    environment:
      DENO_ENV: development
    ports:
      - "7823:8000"
      - "9232:9229" # Deno inspector
    develop:
      watch:
        - path: ../recipe-generator
          target: /app
          action: sync
        - path: ../shared
          target: /app/shared
          action: sync

  shared:
    command: "deno task dev"
    working_dir: /app
    volumes:
      - ../shared:/app
    develop:
      watch:
        - path: ../shared
          target: /app
          action: sync
