services:
  backend:
    build:
      context: ../
      dockerfile: apps/backend/Dockerfile
    volumes:
      - ../apps/backend:/app/apps/backend
    command: deno task dev
    environment:
      BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET:-dev-secret}
      BETTER_AUTH_URL: http://localhost:8000

  frontend:
    build:
      context: ../
      dockerfile: apps/frontend/Dockerfile
    volumes:
      - ../apps/frontend:/app/apps/frontend
    ports:
      - "3500:5173"

  telegram-bot:
    build:
      context: ../
      dockerfile: apps/telegram-bot/Dockerfile
    volumes:
      - ../apps/telegram-bot:/app/apps/telegram-bot

  recipe-generator:
    build:
      context: ../
      dockerfile: apps/recipe-generator/Dockerfile
    volumes:
      - ../apps/recipe-generator:/app/apps/recipe-generator
